version: '3.7'

#to run: docker-compose up -d --build
#to stop: docker-compose stop
#from: https://mherman.org/blog/dockerizing-a-react-app/

services:

  jibber-jabber-client:
    container_name: robin-hood-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
